org: arktalkhub
app: ark-talk-hub
service: ark-talk-hub
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 120
  memorySize: 1024
  stage: ${self:custom.stage}
  deploymentBucket:
    blockPublicAccess: true
  environment:
    CLOUD_STORAGE_BUCKET: ${self:custom.cloudStorage}
    REGION: ${self:custom.region}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - S3:GetObject
            - S3:PutObject
            - S3:DeleteObject
          Resource: !Join ['/', [!GetAtt cloudStorageBucket.Arn, '*']]

functions:
  api:
    handler: dist/handler.handler
    reservedConcurrency: 20
    # Provision a minimum number of concurrent instances (default: 0)
    #provisionedConcurrency: 3 # optional, Count of provisioned lambda instances
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

custom:
  stage: prod
  cloudStorage: cloud-storage-${self:custom.stage}
  region: eu-central-1
  serverless-offline:
    httpPort: 7217
    websocketPort: 8218
    lambdaPort: 8219
    noPrependStageInUrl: true

resources:
  Resources:
    cloudStorageBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:custom.cloudStorage}
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true

package: # Packages each function separately
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - 'src/**/*'
    - '*.eslint'
