org: africana
app: ark-talk-hub
service: ark-talk-hub
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  region: eu-central-1
  timeout: 120
  memorySize: 1024
  stage: ${self:custom.stage}
  deploymentBucket:
    blockPublicAccess: true
  environment:
    REGION: ${self:custom.region}

functions:
  api:
    handler: dist/handler.handler
    reservedConcurrency: 10
    # Provision a minimum number of concurrent instances (default: 0)
    provisionedConcurrency: 10 # optional, Count of provisioned lambda instances
    events:
      - httpApi: '*'

plugins:
  - serverless-offline

custom:
  stage: prod
  region: eu-central-1
  serverless-offline:
    httpPort: 7217
    websocketPort: 8218
    lambdaPort: 8219
    noPrependStageInUrl: true

package: # Packages each function separately
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
    - 'src/**/*'
    - '*.eslint'
